### ISSUE TITLE
Chat demo not working anymore

### ISSUE THREAD

**Issue by ghost** [jeromeetienne/EasyWebsocket#2]
Chat demo was working yesterday, but not today anymore, neither on my desktop nor Android device.

**Comment by jeromeetienne** [comment]
Ok. Thanks for the report. I got isp problem. I cant look more for now.

sent from a phone

On 2011-10-23 9:47 PM, "bardu" <
reply@reply.github.com>
wrote:

Chat demo was working yesterday, but not today anymore, neither on my
desktop nor Android device.

## 

Reply to this email directly or view it on GitHub:
https://github.com/jeromeetienne/EasyWebsocket/issues/2

**Comment by ghost** [comment]
Since we want to built an app with EasyWebsocket, it is important to us to know whether the ISP issue is affecting only your website with the chat demo or node.js?

**Comment by jeromeetienne** [comment]
This is my own isp. No influence of the  server

sent from a phone

On 2011-10-24 3:59 AM, "bardu" <
reply@reply.github.com>
wrote:

Since we want to built an app with EasyWebsocket, it is important to us to
know whether the ISP issue is affecting only your website with the chat demo
or node.js?

##

**Comment by jeromeetienne** [comment]
i just relaunched the server, it should not go down anymore. thanks for the
report

**Comment by ghost** [comment]
Thanks. Is working again.
